Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -62,52 +62,32 @@ jobs:
     runs-on: ubuntu-18.04
     steps:
       - uses: actions/checkout@master
-      - id: Forced_failure
-        name: Forced failing step
-        run: |
-          echo "Output of this action will be localy overwriten to be a failure"
-          echo "::set-output name=set_status::so_it_is_not_neglected"
-
-      - name: Overwrite status
-        id: overwrites
-        env:
-          steps: ${{ toJson(steps) }}
-          needs: ${{ toJson(needs) }}
-        run: |
-          echo "needs<<EOF" >> $GITHUB_ENV
-          echo $needs | jq '.[].result = "failure"' >> $GITHUB_ENV
-          echo "EOF" >> $GITHUB_ENV
-          echo "steps<<EOF" >> $GITHUB_ENV
-          echo $steps | jq '.[].outcome = "failure"' >> $GITHUB_ENV
-          echo "EOF" >> $GITHUB_ENV
-
-      - name: Check overwrites
-        env:
-          steps: ${{ env.steps }}
-          needs: ${{ env.needs }}
-        run: |
-          echo "Needs: $needs"
-          echo "Steps: $steps"
+      - name: Forced failure
+        run: exit 1
 
       - name: MSTeams Notification
         uses: ./
         if: always()
         with:
           webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
-          needs: ${{ env.needs }}
+          needs: ${{ toJson(needs) }}
           job: ${{ toJson(job) }}
-          steps: ${{ env.steps }}
+          steps: ${{ toJson(steps) }}
           dry_run: ${{ !github.event.action == 'release' }}
 
-
       - name: Check if work properly
+        if: failure()
         env:
-          steps: ${{ steps.overwrites.steps }}
-          needs: ${{ steps.overwrites.needs }}
+          steps: ${{ toJson(steps) }}
+          needs: ${{ toJson(needs) }}
+          abc: '{"abc": "why it does not work?"}'
         run: |
           echo 'MSTeams failure notification succeeded'
-          echo $steps
-          echo $needs
+          echo $steps | jq '.[].outcome = "failure"'
+          echo $needs | jq '.[].result = "failure"'
+          echo $abc
+          exit 0
+
 
   without_optional_params:
     name: One with little info
@@ -150,6 +130,7 @@ jobs:
             {
               "@type": "MessageCard",
               "@context": "http://schema.org/extensions",
-              "title": "No ${variables} avaliable in here"
+              "title": "No ${variables} avaliable in here",
+              "text": "Lorem ipssum"
             }
           dry_run: ${{ !github.event.action == 'release' }}
